import libs = libpstld%lib{pstld}

for [dir_path] d: {*/ -build/}
{
  ./: exe{$name($d)-test}: \
    $d/{hxx cxx mm}{*} $libs
}

# Build options.
#

switch $cxx.id: path.match
{
  case 'clang*'
  {
    cxx.coptions += -fobjc-arc
    cxx.loptions += -fobjc-link-runtime
  }
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
